#!/bin/sh

U_NAME=${U_NAME:-app}
G_NAME=${G_NAME:-${U_NAME}}

U_EXIST=$(getent passwd "$U_ID" | cut -f 1 -d ":")
G_EXIST=$(getent passwd "$G_ID" | cut -f 1 -d ":")

if [ -z "$G_EXIST" ]; then
    groupadd -g $G_ID $G_NAME
else
    G_NAME=$G_EXIST
fi

if [ -z "$U_EXIST" ]; then
    useradd -m -u $U_ID -g $G_NAME $U_NAME
else
    usermod -g $G_NAME $U_EXIST > /dev/null 2>&1
fi